-- SRD Inventory Control Centre
-- Supabase schema. Run in SQL Editor for a new project.

create table if not exists public.portal_access (
  email text primary key,
  role text not null default 'viewer' check (role in ('admin','editor','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.procurement_records (
  id bigint generated by default as identity primary key,
  prf_no text, pr_no text, po_no text,
  section text, workshop text, vessel text, asset text, sr_wo text,
  priority text, supplier text, item_code text, item_description text, unit text,
  qty_requested numeric, qty_ordered numeric, qty_received numeric, balance_qty numeric,
  currency text, amount numeric,
  pr_date date, po_date date, required_date date, expected_delivery date,
  payment_status text, delivery_status text, status text, remarks text,
  linked_pr_mtr text, work_order_type text, purchase_from text, purchase_type text,
  processed_date date, requested_by text, modified_by text,
  cancel_reject_reason text, latest_updates text,
  source_type text, source_updated_at timestamptz,
  raw_source jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.material_records (
  id bigint generated by default as identity primary key,
  document_type text not null check (document_type in ('MTR','MRN')),
  document_no text, document_date date,
  workshop text, vessel text, asset text, sr_wo text,
  item_code text, item_description text, unit text,
  requested_qty numeric, transferred_qty numeric, issued_qty numeric, remaining_qty numeric,
  status text, remarks text, source_updated_at timestamptz,
  raw_source jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock_items (
  item_code text primary key,
  item_description text, unit text,
  on_hand numeric not null default 0,
  reserved numeric not null default 0,
  available numeric not null default 0,
  on_order numeric not null default 0,
  unit_cost numeric not null default 0,
  stock_value numeric not null default 0,
  age_band text, last_transaction_date date, source_updated_at timestamptz,
  raw_source jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  physical_date date, transaction_type text,
  item_code text, item_description text, quantity numeric, unit text, cost numeric,
  po_no text, sales_order text, journal_no text, delivery_name text,
  vessel text, sr_wo text, status text,
  raw_source jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.lld_updates (
  id bigint generated by default as identity primary key,
  reference_type text,
  reference_no text not null,
  payment_status text, delivery_status text, eta date, update_text text, source_date date,
  updated_at timestamptz not null default now(),
  unique(reference_type, reference_no)
);

create table if not exists public.case_notes (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_key text not null,
  remark text, action text, owner text, deadline date, eta date, priority text,
  updated_by text, updated_at timestamptz not null default now(),
  unique(entity_type, entity_key)
);

create table if not exists public.source_updates (
  id bigint generated by default as identity primary key,
  source_type text not null, file_name text, source_date date,
  status text not null default 'applied',
  row_count integer not null default 0,
  new_count integer not null default 0,
  changed_count integer not null default 0,
  unchanged_count integer not null default 0,
  unmatched_count integer not null default 0,
  imported_by text, imported_at timestamptz not null default now()
);

create table if not exists public.weekly_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null default current_date,
  label text, metrics jsonb not null default '{}'::jsonb,
  priority_cases jsonb not null default '[]'::jsonb,
  created_by text, created_at timestamptz not null default now()
);

alter table public.portal_access enable row level security;
alter table public.procurement_records enable row level security;
alter table public.material_records enable row level security;
alter table public.stock_items enable row level security;
alter table public.inventory_transactions enable row level security;
alter table public.lld_updates enable row level security;
alter table public.case_notes enable row level security;
alter table public.source_updates enable row level security;
alter table public.weekly_snapshots enable row level security;

-- Access policies are installed in the live project. For a fresh project,
-- add approved emails to portal_access and use RLS policies that require
-- the signed-in email to have an active portal_access row.
